Democracy/Controllers/AdminController.cs
using System.Linq;
using System.Threading.Tasks;
using Democracy.Data;
using Democracy.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Democracy.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private AppDbContext _context;
        private UserManager<IdentityUser> _userManager;

        public AdminController(AppDbContext context, UserManager<IdentityUser> userManager)
        {
	    _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> List()
        {
            var stuff = new AdminList
            {
                Items = _context.Items.Where(item => !item.Done),
                Votes = _context.Votes,
                Users = await _userManager.GetUsersInRoleAsync("User"),
                Admins = await _userManager.GetUsersInRoleAsync("Administrator")
            };
            return View(stuff);
        }

        [HttpPost]
        public IActionResult Approve(int id)
        {
            var itemForApproval = _context.Items.FirstOrDefault(i => i.ItemId == id);
            if (itemForApproval == null) return RedirectToAction("List");

            itemForApproval.Approved = true;
	    _context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult Complete(int id)
        {
            var itemForCompletion = _context.Items.FirstOrDefault(i => i.ItemId == id);
            if (itemForCompletion == null) return RedirectToAction("List");

            itemForCompletion.Done = true;
	    _context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Promote(string email)
        {
            var entry = await _userManager.FindByEmailAsync(email);
            if (entry == null) return RedirectToAction("List");

            await _userManager.RemoveFromRoleAsync(entry, "User");
            await _userManager.AddToRoleAsync(entry, "Administrator");

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Demote(string email)
        {
            var entry = await _userManager.FindByEmailAsync(email);
            if (entry == null) return RedirectToAction("List");

            await _userManager.RemoveFromRoleAsync(entry, "Administrator");
            await _userManager.AddToRoleAsync(entry, "User");

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string email)
        {
            var entry = await _userManager.FindByEmailAsync(email);
            if (entry != null)
            {
                await _userManager.DeleteAsync(entry);
            }

            return RedirectToAction("List");
        }
    }
}

Democracy/Controllers/ItemController.cs
using System.Linq;
using Democracy.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Democracy.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private AppDbContext _context;

        public ItemController(AppDbContext context)
        {
            _context = context;
        }

        public ViewResult List() => View(_context.Items.Where(item => item.Approved && !item.Done));
    }
}

Democracy/Controllers/SuggestionController.cs
using Democracy.Data;
using Democracy.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Democracy.Controllers
{
    [Authorize]
    public class SuggestionController : Controller
    {
        private AppDbContext _context;

        public SuggestionController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult New(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        public IActionResult New(NewSuggestion suggestion, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var newItem = new Item 
                { 
                    Title = suggestion.Title, 
                    Description = suggestion.Description, 
                    Approved = false,
                    Done = false,
                };
		_context.Add(newItem);
		_context.SaveChanges();
                return Redirect(returnUrl ?? "/");
            }
            ViewBag.returnUrl = returnUrl;
            return View();
        }
    }
}

Democracy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" 
        asp-href-include="/lib/bootstrap/dist/**/*.min.css">
    <script asp-src-include="/lib/sortable/js/Sortable.min.js"></script>
    <link rel="stylesheet" asp-href-include="/css/style.css" />
    <title>@ViewData["Title"]</title>
</head>
<body>
<div class="navbar navbar-dark bg-dark navbar-expand-lg" role="navigation">
    <a class="navbar-brand" href="#">Democracy(ish)</a>
    <div class="navbar-nav mr-auto">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="List" asp-controller="Item">Vote</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="New" asp-controller="Suggestion">Suggest</a>
            </li>
        </ul>
    </div>
    <div class="navbar-nav">
        <ul class="navbar-nav">
            @if (!User.Identity.IsAuthenticated) 
            {
                <li class="nav-item">
                    <a class="nav-link" asp-action="Login" asp-controller="Account">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
                </li>
            }
            else
            {
                if (User.IsInRole("Administrator"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="List" asp-controller="Admin">Admin</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link" asp-action="Logout" asp-controller="Account">Logout</a>
                </li>
            }
        </ul>
    </div>
</div>
<div class="row m-1 p-1">
    <div class="mx-auto">
        @RenderBody()
    </div>
</div>

</body>
</html>